@host=http://localhost:5000/api/auth

POST {{host}}/signup
Content-Type: application/json

{
    "name": "Sumit",
    "email": "Sumit@gmail.com",
    "password": "Sumit@123",
    "confirm_password": "Sumit@123"
}

###
POST {{host}}/signin
Content-Type: application/json

{
    "email": "Sumit@gmail.com",
    "password": "Sumit@123"
}