@host=http://localhost:5000/api/user
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyYzk5NjVhYzUxZjFlYmIyN2FlZDc3NyIsIm5hbWUiOiJTdW1pdCIsImVtYWlsIjoiU3VtaXRAZ21haWwuY29tIiwiaWF0IjoxNjU3Mzc4NTM1LCJleHAiOjE2NTczODkzMzV9.j1WqRe0MsV7FYn-fjYvqrw99BugqDTrlvFfhv9Md0Yg

GET {{host}}
Content-Type: application/json
Authorization: Bearer {{token}}